@LojinhaManuel_HostAddress = http://localhost:5029

GET {{LojinhaManuel_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LojinhaManuel_HostAddress}}/api/pedidos/EmpacotarPedidos
Content-Type: application/json

{

}

###
